spring:
  datasource:
    url: jdbc:mysql://at.aliceproject.top:3306/alcprjdb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: ALCPrjDB
    password: 4455661238a
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    resources:
      static-locations: file:${file.uploadFolder},classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
server:
  port: 80
file:
  uploadFolder: /www/wwwroot/SpringBoot/ALCPrj/